/**
 * ditaa - Diagrams Through Ascii Art
 * 
 * Copyright (C) 2004-2011 Efstathios Sideris
 *
 * ditaa is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as 
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * ditaa is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with ditaa.  If not, see <http://www.gnu.org/licenses/>.
 *   
 */
package org.stathissideris.ascii2image;

import java.awt.image.RenderedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collection;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import javax.imageio.ImageIO;

import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;
import static org.junit.Assert.*;
import org.stathissideris.ascii2image.core.ConversionOptions;
import org.stathissideris.ascii2image.graphics.BitmapRenderer;
import org.stathissideris.ascii2image.graphics.Diagram;
import org.stathissideris.ascii2image.text.TextGrid;

import static yskkin.ascii2image.ImageMatcher.*;

/**
 * If ran as a Java application, it produces an HTML report for manual 
 * inspection. If ran as a junit test it runs a pixel-by-pixel
 * comparison between the images in the "images-expected" and the
 * images generated by the test.
 * 
 * @author Efstathios Sideris
 */
@RunWith(Parameterized.class)
public class VisualTester {

	private static final String HTMLReportName = "test_suite";
	private static final String expectedDir = "/tests/images-expected";
	private static final File failedImageDir = new File("build", "failed-images");
	
	private File textFile;
	
	public static void main(String[] args) throws Exception {
		String reportDir = "tests/images";
		VisualTester.createHTMLTestReport(getFilesToRender(), reportDir, HTMLReportName);
		
		System.out.println("Tests completed");
	}

	@BeforeClass
	public static void setUp() {
		failedImageDir.mkdirs();
		for (File previousTest : failedImageDir.listFiles()) {
			previousTest.delete();
		}
	}

	@Test
	public void compareImages() throws Exception {
		ConversionOptions options = new ConversionOptions();
		String actualBaseName = textFile.getName().substring(0, textFile.getName().lastIndexOf(".")) + ".png";
		File actualFile = new File(failedImageDir, actualBaseName);
		File expectedFile = new File(getClass().getResource(expectedDir + "/" + textFile.getName() + ".png").toURI());

		if(!expectedFile.exists()){
			System.out.println("Skipping " + textFile + " -- reference image does not exist");
			throw new FileNotFoundException("Reference image "+expectedFile+" does not exist");
		}
		
		TextGrid grid = new TextGrid();
		grid.loadFrom(textFile.toString());
		Diagram diagram = new Diagram(grid, options);

		RenderedImage image = new BitmapRenderer().renderToImage(diagram, options.renderingOptions);		
	
		ImageIO.write(image, "png", actualFile);
		assertThat(actualFile, hasSameImageAs(expectedFile));
		actualFile.delete(); // Delete succeeded case.
	}
	
	public VisualTester(File textFile) {
		this.textFile = textFile;
	}
	
	@Parameters
	public static Collection<File[]> getTestParameters() throws Exception {
		List<File> filesToRender = getFilesToRender();
		List<File[]> result = new ArrayList<File[]>();

		for (int i = 0; i < filesToRender.size(); i++) {
			result.add(new File[]{ filesToRender.get(i) });
		}

		return result;
	}
	
	public static List<File> getFilesToRender() throws Exception {
		String textDir = "/tests/text";
		
		File textDirObj = new File(VisualTester.class.getResource(textDir).toURI());
		ArrayList<File> textFiles
			= new ArrayList<File>(Arrays.asList(textDirObj.listFiles()));
	
		Set<String> excludedFiles = new HashSet<String>();
		excludedFiles.addAll( Arrays.asList(new String[]{
			"sjis.txt"
		}));
		
		Iterator<File> it = textFiles.iterator();
		while(it.hasNext()){
			String filename = it.next().toString();
			if(!filename.matches(".+\\.txt$") || isInExcluded(filename, excludedFiles)){
				it.remove();
			}
		}

		return textFiles;
	}
	
	private static boolean isInExcluded(String filename, Set<String> excludedSet) {
		for(String excluded : excludedSet) {
			if(filename.endsWith(excluded)) return true;
		}
		return false;
	}
	
	public static void generateImages(List<File> textFiles, String destinationDir) {
		
		ConversionOptions options = new ConversionOptions();
		
		for(File textFile : textFiles) {
			TextGrid grid = new TextGrid();

			File toFile = new File(destinationDir + File.separator + textFile.getName() + ".png");
			
			
			long a = java.lang.System.nanoTime();
			long b;
			try {
				System.out.println("Rendering "+textFile+" to "+toFile);
				
				grid.loadFrom(textFile.toString());
				Diagram diagram = new Diagram(grid, options);

				RenderedImage image = new BitmapRenderer().renderToImage(diagram, options.renderingOptions);
				
				b = java.lang.System.nanoTime();
		        java.lang.System.out.println( "Done in " + Math.round((b - a)/10e6) + "msec");
				
				try {
					File file = new File(toFile.getAbsolutePath());
					ImageIO.write(image, "png", file);
				} catch (IOException e) {
					//e.printStackTrace();
					System.err.println("Error: Cannot write to file "+toFile);
					System.exit(1);
				}
				
			} catch (Exception e) {
				System.err.println("!!! Failed to render: "+textFile+" !!!\n");
				System.err.println(grid.getDebugString()+"\n");
				e.printStackTrace(System.err);
				
				continue;
			}			
		}

	}
	
	
	public static boolean createHTMLTestReport(List<File> textFiles, String reportDir, String reportName){

		ConversionOptions options = new ConversionOptions();

		String reportFilename = reportDir+"/"+reportName+".html";

		if(!(new File(reportDir).exists())){
			File dir = new File(reportDir);
			dir.mkdir();
		}

		PrintWriter s = null;
		try {
			s = new PrintWriter(new FileWriter(reportFilename));
		} catch (IOException e) {
			System.err.println("Cannot open file "+reportFilename+" for writing:");
			e.printStackTrace();
			return false;
		}

		s.println("<html><body>");
		s.println("<h1>ditaa test suite</h1>");
		s.println("<h2>generated on: "+Calendar.getInstance().getTime()+"</h2>");


		for(File textFile : textFiles) {
			TextGrid grid = new TextGrid();

			File toFile = new File(reportDir + File.separator + textFile.getName() + ".png");
			
			
			long a = java.lang.System.nanoTime();
			long b;
			try {
				System.out.println("Rendering "+textFile+" to "+toFile);
				
				grid.loadFrom(textFile.toString());
				Diagram diagram = new Diagram(grid, options);

				RenderedImage image = new BitmapRenderer().renderToImage(diagram, options.renderingOptions);
				
				b = java.lang.System.nanoTime();
		        java.lang.System.out.println( "Done in " + Math.round((b - a)/10e6) + "msec");
				
				try {
					File file = new File(toFile.getAbsolutePath());
					ImageIO.write(image, "png", file);
				} catch (IOException e) {
					//e.printStackTrace();
					System.err.println("Error: Cannot write to file "+toFile);
					System.exit(1);
				}
				
			} catch (Exception e) {
				s.println("<b>!!! Failed to render: "+textFile+" !!!</b>");
				s.println("<pre>\n"+grid.getDebugString()+"\n</pre>");
				s.println(e.getMessage());
				s.println("<hr />");
				s.flush();
				
				System.err.println("!!! Failed to render: "+textFile+" !!!");
				e.printStackTrace(System.err);
				
				continue;
			}
			
			s.println(makeReportTable(textFile.getName(), grid, toFile.getName(), b - a));
			s.println("<hr />");
			s.flush();
		}
		
		s.println("</body></html>");

		s.flush();
		s.close();
		
		
		System.out.println("Wrote HTML report to " + new File(reportFilename).getAbsolutePath());
		
		return true;

	}

	private static String makeReportTable(String gridURI, TextGrid grid, String imageURI, long time){
		StringBuffer buffer = new StringBuffer("<center><table border=\"0\">");
		buffer.append("<th colspan=\"2\"><h3>"+gridURI+" ("+Math.round(time/10e6)+"msec)</h3></th>");
		buffer.append("<tr><td><pre>\n"+grid.getDebugString()+"\n</pre></td>");
		buffer.append("<td><img border=\"0\" src=\""+imageURI+"\"</td></tr>");
		buffer.append("</table></center>");
		return buffer.toString();
	}

}
